default_platform(:android)

platform :android do

  changelog = ""
  lane_context[:build_type] = ""
#   lane_context[:version_name] = android_get_version_name(gradle_file: "./")
#   lane_context[:version_code] = android_get_version_code(gradle_file: "./")

  lane_context[:members] = {}

  lane_context[:commit] = last_git_commit

  lane_context[:qas] = [""].join(" ")

  lane_context[:author] = lane_context[:members].filter { |key| key == lane_context[:commit][:author_email] }.values.first

  lane_context[:reviewers] = lane_context[:members].reject { |key| key == lane_context[:commit][:author_email] }.values.join(" ")

  desc "Runs all tests"
  lane :test do
    build_app_debug
    run_detekt
    run_kover_unit_tests
#     on_successful_test()
#     generate_unit_tests_report
  end

  desc "Publish on App Distribution"
  lane :beta do |options|
    if options[:debug]
      build_app_debug
    else
      build_app_release
    end
    save_changelog_from_git_commits
    publish_on_app_distribution
    on_successful_publish_on_app_distribution()
  end

  desc "Build a release and publish on Play Store"
  lane :deploy do
    build_app_release
    publish_on_play_store
    on_successful_publish_on_play_store()
  end

  after_all do |lane|
    stop_gradle
  end

  error do |lane, exception|
    on_error(lane, exception)
    stop_gradle
  end

  desc "Build App Debug"
  private_lane :build_app_debug do
    lane_context[:build_type] = "debug"
    gradle(task: "clean bundleDebug")
  end

  desc "Build App Release"
  private_lane :build_app_release do
    lane_context[:build_type] = "release"
    gradle(task: "clean bundleRelease")
  end

  desc "Run Detekt"
  private_lane :run_detekt do
    gradle(task: "detekt")
  end

  desc "Run Kover Unit Tests"
  private_lane :run_kover_unit_tests do
    gradle(task: "koverVerify")
  end

  desc "Generate Unit Tests Report"
  private_lane :generate_unit_tests_report do
    gradle(task: "koverHtmlReport")
  end

  desc "Save Changelog From Git Commits"
  private_lane :save_changelog_from_git_commits do
    changelog += "Versão de #{lane_context[:build_type]}\n\n"
    changelog += "Mudanças: \n"
    changelog += lane_context[:commit][:message]
  end

  desc "Publish on App Distribution"
  private_lane :publish_on_app_distribution do
    firebase_app_distribution(
      service_credentials_file: ENV['PRIVATE_KEY_APP_DIST'],
      app: ENV['FIREBASE_APP_ID'],
      groups: ENV['FIREBASE_APP_GROUP_TESTERS'],
      release_notes: changelog,
      android_artifact_type: ENV['FIREBASE_ANDROID_ARTIFACT_TYPE']
    )
  end

  desc "Publish on Play Store"
  private_lane :publish_on_play_store do
    upload_to_play_store(
      track: ENV['PLAY_STORE_TRACK'],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      rollout: ENV['PLAY_STORE_ROLLOUT']
    )
  end

  desc "Stop Gradle"
  private_lane :stop_gradle do
    sh("./../gradlew --stop")
  end

  def on_error(lane, exception)
    slack(
      message: "Foi identificado um problema durante a execução da pipeline na lane *#{lane}*. \nSolicita-se uma revisão para compreender a origem do erro",
      success: false,
      slack_url: ENV['SLACK_URL'],
      default_payloads: [:last_git_commit],
      attachment_properties: {
        fields: [
          {
            title: "Author",
            value: lane_context[:author],
            short: true
          },
          {
            title: "Error message",
            value: exception.to_s,
            short: false
          }
        ]
      }
    )
  end

  def on_successful_test
    slack(
      message: "O Pull Request acaba de passar pela análise com sucesso e está pronto para revisão! \nPor favor, sintam-se à vontade para dar uma olhada e deixar seus comentários.",
      success: true,
      slack_url: ENV['SLACK_URL'],
      default_payloads: [:git_author],
      attachment_properties: {
        fields: [
          {
            title: "Reviewers",
            value: lane_context[:reviewers],
            short: true
          },
          {
            title: "Changes",
            value: lane_context[:commit][:message],
            short: true
          }
        ]
      }
    )
  end

  def on_successful_publish_on_app_distribution
    slack(
      message: "A versão de #{lane_context[:build_type]} #{lane_context[:version_name]} (#{lane_context[:version_code]}) foi liberada no App Distribution",
      success: true,
      slack_url: ENV['SLACK_URL'],
      default_payloads: [],
      attachment_properties: {
        fields: [
          {
            title: "Members",
            value: lane_context[:members].values.join(" "),
            short: true
          },
          {
            title: "QAs",
            value: lane_context[:qas],
            short: true
          },
          {
            title: "Changes",
            value: lane_context[:commit][:message],
            short: true
          }
        ]
      }
    )
  end

  def on_successful_publish_on_play_store
    slack(
      message: "A versão #{lane_context[:version_name]} (#{lane_context[:version_code]}) foi liberada na track #{ENV['PLAY_STORE_TRACK']} da Play Store. \nPara instalar a nova versão acesse: https://play.google.com/apps/internaltest/4701283061108671068",
      success: true,
      slack_url: ENV['SLACK_URL'],
      default_payloads: [],
      attachment_properties: {
        fields: [
          {
            title: "Members",
            value: lane_context[:members].values.join(" "),
            short: true
          },
          {
            title: "QAs",
            value: lane_context[:qas],
            short: true
          }
        ]
      }
    )
  end
end
