name: Continuous Integration

on:
  pull_request:
    branches:
      ['main', 'develop']

jobs:
  continuous-integration:
    runs-on: macos-latest
    steps:
      - name: Set up git and fetch all history for all branches and tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bundle install
        timeout-minutes: 5
        run: bundle install
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Deploy to TestFlight
        run: |
          bundle exec fastlane android test