name: Continuous Integration

on:
  pull_request:
    branches:
      [ main, develop ]

jobs:
  continuous-integration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/shared
        with:
          project_config_path: ${{ vars.PROJECT_CONFIG_PATH }}
      - name: Build and Deploy to TestFlight
        run: |
          bundle exec fastlane android test